services:
  - type: web
    name: video-hub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server_render.py
    envVars:
      - key: PORT
        value: 10000
